### PR TITLE
Fix Compatibility with Spark 3.2.1

### LINKED ISSUE #364: [BUG] Unable to read vertica table into Spark dataframe in Spark 3.2.1
## Environment
- Spark version: 3.2.1
- Hadoop version: 3.2.2
- Vertica version: 10.X/11.X
- Vertica Spark Connector version: 3.1.0
- Java version: 1.8
- Additional Environment Information:

---

## Problem Description
- Reading from Vertica into Spark dataframe in Spark 3.2.1 is throwing an error
- Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.creteDateRebaseFuncInRead(Lscala/Enumeration$Value;Ljava/lang/String;)Lscala/Function1;

1. Steps to reproduce: Read vertica table into Spark, try to count or show
2. Expected behaviour: Provide the count or show
3. Actual behaviour: Error due to what appears to be a typo in the Vertica code
4. Error message/stack trace:
5. Caused by: java.lang.NoSuchMethodError: org.apache.spark.sql.execution.datasources.DataSourceUtils$.creteDateRebaseFuncInRead(Lscala/Enumeration$Value;Ljava/lang/String;)Lscala/Function1;
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetRowConverter.<init>(ParquetRowConverter.scala:193)
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetRecordMaterializer.<init>(ParquetRecordMaterializer.scala:58)
        at org.apache.spark.sql.execution.datasources.parquet.vertica.ParquetReadSupport.prepareForRead(ParquetReadSupport.scala:141)
        at com.vertica.spark.datasource.fs.HadoopFileStoreLayer.$anonfun$openReadParquetFile$1(FileStoreLayerInterface.scala:327)
        at scala.util.Try$.apply(Try.scala:213)
        at com.vertica.spark.datasource.fs.HadoopFileStoreLayer.openReadParquetFile(FileStoreLayerInterface.scala:316)
        at com.vertica.spark.datasource.core.VerticaDistributedFilesystemReadPipe.$anonfun$startPartitionRead$2(VerticaDistributedFilesystemReadPipe.scala:375)
        at scala.util.Either.flatMap(Either.scala:341)
        at com.vertica.spark.datasource.core.VerticaDistributedFilesystemReadPipe.startPartitionRead(VerticaDistributedFilesystemReadPipe.scala:362)
        at com.vertica.spark.datasource.core.DSReader.openRead(DSReader.scala:65)
        at com.vertica.spark.datasource.v2.VerticaBatchReader.<init>(VerticaDatasourceV2Read.scala:232)
        at com.vertica.spark.datasource.v2.VerticaReaderFactory.createReader(VerticaDatasourceV2Read.scala:220)
        at org.apache.spark.sql.execution.datasources.v2.DataSourceRDD.compute(DataSourceRDD.scala:64)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:52)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:373)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:337)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:90)
        at org.apache.spark.scheduler.Task.run(Task.scala:131)
        at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$3(Executor.scala:506)
        at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:1462)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:509)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        ... 1 more
6. Code sample or example on how to reproduce the issue:
df1 = spark.read.load(format="com.vertica.spark.datasource.VerticaSource",
 host=host,
 user=user,
 password=password,
 db=db,
 dbschema="my_schema",
 table="my_table",
 staging_fs_url=staging_fs_url)

df1.count)
---

## Spark Connector Logs
- Add related logs entries here.

### PR DESCRIPTION
**Pull request by Aryex**
### Summary

Fixes compatibility with Spark3.2.1

### Description

Added VerticaDataSourceUtils, which copied only the needed coded form Spark 3.2.0

### Related Issue

Closes #364 

### Additional Reviewers
@alexr-bq 
@jeremyp-bq 
@jonathanl-bq

### CODE REVIEW

File: connector/src/main/scala/com/vertica/spark/parquet/VerticaDataSourceUtils.scala [hunk 1]
```diff
@@ -0,0 +1,52 @@
...
+/**
+ * Copied from Spark 3.2.0 DataSourceUtils implementation.
+ *
+ * Classes under the parquet package were copied from Spark for reading parquet into Spark. It is not a public API and
+ * thus is expected to change. In Spark 3.2.1, the DataSourceUtils interface was changed. As a fix, this class
+ * copied from Spark 3.2.0 only the needed functions.
+ * */
+object VerticaDataSourceUtils {
+
+  def createDateRebaseFuncInRead(
```
Comment (alexey-temnikov) [inline connector/src/main/scala/com/vertica/spark/parquet/VerticaDataSourceUtils.scala:29]: As we have to maintain the code, let's scaladocs for both methods.

File: connector/src/main/scala/com/vertica/spark/parquet/ParquetRowConverter.scala [hunk 2]
```diff
@@ -21,16 +21,13 @@ package org.apache.spark.sql.execution.datasources.parquet.vertica
...
-
 import scala.collection.JavaConverters._
 import scala.collection.mutable.ArrayBuffer
-
 import org.apache.parquet.column.Dictionary
 import org.apache.parquet.io.api.{Binary, Converter, GroupConverter, PrimitiveConverter}
 import org.apache.parquet.schema.{GroupType, OriginalType, Type}
 import org.apache.parquet.schema.OriginalType.LIST
 import org.apache.parquet.schema.PrimitiveType.PrimitiveTypeName.{BINARY, FIXED_LEN_BYTE_ARRAY, INT32, INT64, INT96}
-
```
Comment (alexey-temnikov) [inline connector/src/main/scala/com/vertica/spark/parquet/ParquetRowConverter.scala:33]: Seems like the empty line was used to separate the group of imports. If it is spacing is consistently used, it might be a good idea to revert the change.

**Review by alexey-temnikov — APPROVED** [review]

File: connector/src/main/scala/com/vertica/spark/parquet/ParquetRowConverter.scala (hunk 2 above)
Comment (Aryex) [reply connector/src/main/scala/com/vertica/spark/parquet/ParquetRowConverter.scala]: Added back

File: connector/src/main/scala/com/vertica/spark/parquet/VerticaDataSourceUtils.scala (hunk 1 above)
Comment (Aryex) [reply connector/src/main/scala/com/vertica/spark/parquet/VerticaDataSourceUtils.scala:32]: Added

File: connector/build.sbt [hunk 3]
```diff
@@ -30,8 +30,8 @@ resolvers += "jitpack" at "https://jitpack.io"
 
 libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2"
 libraryDependencies += "com.vertica.jdbc" % "vertica-jdbc" % "11.0.2-0"
-libraryDependencies += "org.apache.spark" %% "spark-core" % "3.2.0"
-libraryDependencies += "org.apache.spark" %% "spark-sql" % "3.2.0"
+libraryDependencies += "org.apache.spark" %% "spark-core" % "latest.release"
+libraryDependencies += "org.apache.spark" %% "spark-sql" % "latest.release"
```
Comment (jeremyp-bq) [inline connector/build.sbt:34]: Just looked at our README, I think we should update the Limitations section for the Spark version and complex types support:
> The connector supports versions of Spark between 3.0 and 3.1.1.
> The connector supports basic Spark types. Complex types are not currently supported (arrays, maps, structs).

We can remove these lines and just add the minimum Spark version (3.0.0) under the Getting Started or Spark section.  The complex types already have their own section now.

Comment (Aryex) [reply connector/build.sbt:34]: Good call. Fixed

**Review by jeremyp-bq — APPROVED** [review]
