### PR TITLE
Fix create table statement string parsing

### LINKED ISSUE #475: [BUG] Could not get external table schema: String index out of range: -1
## Environment
- Spark version: Spark 3.1.2/3.2.1
- Hadoop version: 3.2.0/3.3.1
- Vertica version: 11
- Vertica Spark Connector version: spark-vertica-connector-all-3.3.1.jar
- Java version: 1.8
- Additional Environment Information:

---

## Problem Description
Trying to create an external table from existing data is having an error

Caused by: com.vertica.spark.util.error.ConnectorException: Could not get external table schema: String index out of range: -1
        at com.vertica.spark.util.error.ErrorHandling$.logAndThrowError(ErrorHandling.scala:78)
        at com.vertica.spark.datasource.v2.VerticaBatchWrite.commit(VerticaDatasourceV2Write.scala:92)
        at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:369)
        ... 44 more
        Suppressed: com.vertica.spark.util.error.ConnectorException: Writing job aborted. Check spark worker log for specific error.
                at com.vertica.spark.util.error.ErrorHandling$.logAndThrowError(ErrorHandling.scala:78)
                at com.vertica.spark.datasource.v2.VerticaBatchWrite.abort(VerticaDatasourceV2Write.scala:104)
                at org.apache.spark.sql.execution.datasources.v2.V2TableWriteExec.writeWithV2(WriteToDataSourceV2Exec.scala:376)
                ... 44 more

1. Steps to reproduce: Create empty schema df, write df using  create_external_table="existing-data" and specify path to existing data on staging_fs_url option
2. Expected behaviour: Create the external table
3. Actual behaviour: Error due to the can't get external table schema
4. Error message/stack trace: See above
5. Code sample or example on how to reproduce the issue: Just trying to do the basic write from the example; using another dataset is working fine, just this specific dataset is causing this Could not get external table schema: String index out of range: -1 mesage
6. If I go into vsql and run the select_infer_schema command and copy/paste the DDL, then it loads fine

---

## Spark Connector Logs
- Add related logs entries here.

### PR DESCRIPTION
**Pull request by Aryex**
### Summary

Fixes #475 

`SchemaTools.inferExternalTableSchema` did not account for nested parenthesis in create-external-table string, thus failing. It should now be able to handle such cases. 

Added `StringParsingUtils` that contains general purpose parsing methods. For reviewing, start at `SchemaTools.inferExternalTableSchema()`

Tests are updated to include the failing cases.

### Related Issue

Close #475 

### Additional Reviewers

@alexey-temnikov 
@jonathanl-bq 
@jeremyp-bq 
@alexr-bq

### CODE REVIEW

File: connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala [hunk 1]
```diff
@@ -620,48 +620,81 @@ class SchemaTools(ctTools: ComplexTypesSchemaTools = new ComplexTypesSchemaTools
...
+          case ',' =>
+            if(parenCount > 0){
+              recursion(tail.head, tail.tail, currStr + char, splits, parenCount)
+            }else{
+              recursion(tail.head, tail.tail, "", splits :+ currStr, parenCount)
+            }
+          case _ =>
+            val nextStr = char match {
+              // Don't include newline
+              case '\n' => currStr
```
Comment (Aryex) [inline connector/src/main/scala/com/vertica/spark/util/schema/SchemaTools.scala:673]: Not sure if newline should be removed or not. It doesn't seem to affect the query but was added by Vertica for readability.

**Review by jeremyp-bq — APPROVED** [review]
